default_language_version:
  python: python3.12


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        types: [python]
        exclude: docs/
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        types: [python]
        exclude: docs|scripts|tests

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    - id: poetry-check
    - id: poetry-install
    - id: poetry-lock

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "./requirements.txt"]

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.7
    hooks:
    - id: pydoclint
      args: ["--style", "google", "./mtpy"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      additional_dependencies: ["gibberish-detector"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
