site_name: MTPy
repo_url: https://github.com/Cian-H/MTPy
repo_name: Cian-H/MTPy
edit_uri: edit/main/docs/
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  plugins:
    - optimize
    - privacy
    - projects
    - typeset

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Documentation:
    - CLI: documentation/cli.md
    - Reference: documentation/reference/
  - Status:
    - UML: uml.md
    - Type Reports: type_reports.md
  # - FAQ: faq.md
  # - Troubleshooting: troubleshooting.md
  # - Changelog: changelog.md
  # - License: license.md

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - callouts

plugins:
  - search
  - autorefs
  - macros
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_uml_diagrams.py
        - scripts/gen_type_reports.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
        securityLevel: "loose"
  - panzoom:
      mermaid: true
      full_screen: true
      always_show_hint: true
  - termynal
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules: ["mtpy", ]
            show_inheritance_diagram: true
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-typer2:
      pretty: true

extra_javascript:
    - extra/refresh_on_toggle_dark_light.js
