site_name: MTPy
repo_url: https://github.com/Cian-H/MTPy
repo_name: Cian-H/MTPy
edit_uri: edit/main/docs/
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  plugins:
    - optimize
    - privacy
    - projects
    - typeset

nav:
  - Home: index.md
  - Documentation:
    - Reference: reference/
    - Structure:
      - Classes: tmp/uml/classes.html
      - Packages: tmp/uml/packages.html
  # - FAQ: faq.md
  # - Troubleshooting: troubleshooting.md
  # - Changelog: changelog.md
  # - License: license.md

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#   - mkdocs-typer

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_uml_diagrams.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules: ["mtpy", ]
            show_inheritance_diagram: true
  - git-revision-date-localized:
      enable_creation_date: true
