repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/charliermarsh/ruff
    rev: main
    hooks:
      - id: ruff
        language_version: python3.9
  - repo: https://github.com/sphinx-toolbox/sphinx-pyproject
    rev: master
    hooks:
      - id: sphinx-pyproject
        language_version: python3.9