[tool.poetry]
name = "mtpy"
version = "0.1.0"
description = ""
authors = ["Cian Hughes <cian.hughes@dcu.ie>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
julia = "^0.5.7"
numpy = "^1.23.1"
matplotlib = "^3.5.2"
plotly = "^5.9.0"
dask = "^2022.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
memory-profiler = "^0.60.0"
maturin = "^0.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
