[tool.poetry]
name = "Aconity_IR_Analysis"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.2.0"
numpy = "^1.19.5"
Shapely = "^1.7.1"
scipy = "^1.6.0"
matplotlib = "^3.3.3"
ipython = "^7.19.0"
jupyterhub = "^1.3.0"
ipykernel = "^5.4.2"
tqdm = "^4.56.0"
plotly = "^4.14.3"
scikit-learn = "^0.24.1"
pip = "^21.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
