[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[project]
name = "mtpy"
version = "0.1.0"
description = ""
license = "MIT"
[[project.source]]
name = "nvidia"
url = "https://pypi.ngc.nvidia.com"
default = false
secondary = false

[[project.authors]]
name = "Cian Hughes"
email = "cian.hughes@dcu.ie"

[tool.black]
line-length = 100
target-version = [ "py39",]
include = "\\.pyi?$"
exclude = "\\.venv/\n|\\.toml$\n|\\.sh$\n|\\.git$\n|\\.ini$\n|\\.json$\n|\\.txt$\n|\\.jl$\n|\\.rs$\n|\\.md$\n"

[tool.ruff]
select = [ "E", "F",]
ignore = []
fixable = [ "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT",]
unfixable = []
exclude = [ ".bzr", ".direnv", ".eggs", ".git", ".hg", ".mypy_cache", ".nox", ".pants.d", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build", "buck-out", "build", "dist", "node_modules", "venv", ".vscode",]
line-length = 100
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py39"

[tool.sphinx-pyproject]
source-dir = "docs"
extensions = [ "sphinx.ext.autodoc", "sphinx.ext.napoleon",]
html_theme = "classic"

[project.dependencies]
python = "3.9.*"
julia = "^0.5.7"
numpy = "^1.23.1"
matplotlib = "^3.5.2"
plotly = "^5.9.0"
tqdm = "^4.64.0"
psutil = "^5.9.1"
pandas = "^1.4.3"
tables = "^3.7.0"
lz4 = "^4.0.2"
bokeh = "^2.4.3"
holoviews = "^1.15.1"
datashader = "^0.14.2"
jupyterlab = "^3.4.8"
dash = "^2.6.2"
jupyterlab-dash = "^0.1.0-alpha.3"
pyvista = "^0.36.1"
ipyvtklink = "^0.2.3"
pyvista-xarray = "^0.1.2"
openpyxl = "^3.0.10"
odfpy = "^1.4.1"
cudf-cu11 = "^22.10.0"
dask-cudf-cu11 = "^22.10.0"
fsspec = "^2022.11.0"
sphinx-pyproject = "^0.1.0"

[project.dev-dependencies]
pytest = "^7.1.2"
memory-profiler = "^0.60.0"
maturin = "^0.13.0"
graphviz = "^0.20"
bokeh = "^2.4.3"
line-profiler = "^3.5.1"
snakeviz = "^2.1.1"
jupyter = "^1.0.0"
ipykernel = "^6.16.0"

[tool.ruff.mccabe]
max-complexity = 10

[project.dependencies.dask]
extras = [ "distributed", "graphviz",]
version = "^2022.7.0"

[project.dependencies.read_layers]
file = "wheels/read_layers-0.1.0-cp39-cp39-linux_x86_64.whl"

[project.group.dev.dependencies]
sphinx = "^6.2.1"
pre-commit = "^3.2.2"
sphinx-rtd-theme = "^1.2.0"
docstring-generator = "^0.2.2"
