name: Python package build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Build for ${{ matrix.os }} with Python ${{ matrix.python-version }} via uv
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14", "3.14t"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v7
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Install Act dependencies
      if: ${{ env.ACT }}
      run: |
        apt-get update && apt-get install sudo -y cargo
    - name: Install dependencies
      run: |
        uv sync
    - name: Test with pytest
      run: |
        uv run pytest
